import type { Metadata } from 'next';
import './globals.css';
import { ReactNode } from 'react';
import Providers from '@/components/utils/Providers';
import { getServerToken } from '@/lib/session/token';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const token = getServerToken();

  return (
    <html lang="en">
      <body>
        <Providers session={token}>{children}</Providers>
      </body>
    </html>
  );
}
