import type { Metadata } from 'next';
import './globals.css';
import React, { ReactNode } from 'react';
import Providers from '@/components/utils/Providers';
import SessionProvider from '@/components/utils/SessionProvider';
import { verifySession } from '@/lib/session';
import Header from '@/app/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): Promise<React.JSX.Element> {
  const session = await verifySession();

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <Providers>
            <Header />
            {children}
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
